title: Chiara Mansi
description: PhD student at the University of Tuscia
theme: jekyll-theme-minimal 

# Immagine del profilo (Assicurati di caricare la foto nella cartella assets/)
logo: /assets/avatar.jpg

# Contatti e Social
email: chiara.mansi@unitus.it
github_username: chiaramansi
orcid: "0000-0003-0333-8261"

# Link accademici personalizzati
google_scholar: "https://scholar.google.com/citations?hl=it&user=_F51acAAAAAJ"
researchgate: "https://www.researchgate.net/profile/Chiara-Mansi-3"



